apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  - port: 81
    targetPort: 81
    nodePort: 30081
    protocol: TCP
    name: transport-tcp
  - port: 443
    targetPort: 443
    nodePort: 30443
    protocol: TCP
    name: https
  - port: 8081
    targetPort: 8081
    nodePort: 32081
    protocol: TCP
    name: readiness-port
  - port: 8080
    targetPort: 8080
    nodePort: 32080
    protocol: TCP
    name: dashboard
  - port: 9113
    targetPort: 9113
    nodePort: 32113
    protocol: TCP
    name: prometheus
  selector:
    app: nginx-ingress


